// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsStatistics.Infrastructure.Database;

#nullable disable

namespace SportsStatistics.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224144943_CorrectedMatchMinuteColumnNames")]
    partial class CorrectedMatchMinuteColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsStatistics.Domain.Competitions.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int>("Format")
                        .HasColumnType("int")
                        .HasColumnName("Format");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SeasonId");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "SportsStatistics.Domain.Competitions.Competition.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Competitions", "sports");
                });

            modelBuilder.Entity("SportsStatistics.Domain.Fixtures.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompetitionId");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int>("Location")
                        .HasColumnType("int")
                        .HasColumnName("Location");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.ComplexProperty<Dictionary<string, object>>("KickoffTimeUtc", "SportsStatistics.Domain.Fixtures.Fixture.KickoffTimeUtc#KickoffTimeUtc", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("KickoffTimeUtc");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Opponent", "SportsStatistics.Domain.Fixtures.Fixture.Opponent#Opponent", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Opponent");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Fixtures", "sports");
                });

            modelBuilder.Entity("SportsStatistics.Domain.MatchTracking.MatchEvents.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FixtureId");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccurredAtUtc");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.ToTable("MatchEvents", "sports");
                });

            modelBuilder.Entity("SportsStatistics.Domain.MatchTracking.PlayerEvents.PlayerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FixtureId");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccurredAtUtc");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlayerId");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerEvents", "sports");
                });

            modelBuilder.Entity("SportsStatistics.Domain.MatchTracking.SubstitutionEvents.SubstitutionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FixtureId");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccurredAtUtc");

                    b.HasKey("Id");

                    b.ToTable("SubstitutionEvents", "sports");
                });

            modelBuilder.Entity("SportsStatistics.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("Position");

                    b.ComplexProperty<Dictionary<string, object>>("DateOfBirth", "SportsStatistics.Domain.Players.Player.DateOfBirth#DateOfBirth", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("DateOfBirth");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "SportsStatistics.Domain.Players.Player.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Nationality", "SportsStatistics.Domain.Players.Player.Nationality#Nationality", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nationality");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SquadNumber", "SportsStatistics.Domain.Players.Player.SquadNumber#SquadNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("SquadNumber");
                        });

                    b.HasKey("Id");

                    b.ToTable("Players", "sports");
                });

            modelBuilder.Entity("SportsStatistics.Domain.Seasons.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.ComplexProperty<Dictionary<string, object>>("DateRange", "SportsStatistics.Domain.Seasons.Season.DateRange#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("EndDate");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("StartDate");
                        });

                    b.HasKey("Id");

                    b.ToTable("Seasons", "sports");
                });

            modelBuilder.Entity("SportsStatistics.Domain.Teamsheets.Teamsheet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FixtureId");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("SubmittedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId")
                        .IsUnique();

                    b.ToTable("Teamsheets", "sports");
                });

            modelBuilder.Entity("SportsStatistics.Domain.Teamsheets.TeamsheetPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("bit")
                        .HasColumnName("IsStarter");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlayerId");

                    b.Property<Guid>("TeamsheetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TeamsheetId");

                    b.HasKey("Id");

                    b.HasIndex("TeamsheetId", "PlayerId")
                        .IsUnique();

                    b.ToTable("TeamsheetPlayers", "sports");
                });

            modelBuilder.Entity("SportsStatistics.Domain.Competitions.Competition", b =>
                {
                    b.HasOne("SportsStatistics.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportsStatistics.Domain.Fixtures.Fixture", b =>
                {
                    b.HasOne("SportsStatistics.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SportsStatistics.Domain.Fixtures.Score", "Score", b1 =>
                        {
                            b1.Property<Guid>("FixtureId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AwayGoals")
                                .HasColumnType("int")
                                .HasColumnName("AwayGoals");

                            b1.Property<int>("HomeGoals")
                                .HasColumnType("int")
                                .HasColumnName("HomeGoals");

                            b1.HasKey("FixtureId");

                            b1.ToTable("Fixtures", "sports");

                            b1.WithOwner()
                                .HasForeignKey("FixtureId");
                        });

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("SportsStatistics.Domain.MatchTracking.MatchEvents.MatchEvent", b =>
                {
                    b.HasOne("SportsStatistics.Domain.Fixtures.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SportsStatistics.Domain.MatchTracking.Minute", "Minute", b1 =>
                        {
                            b1.Property<Guid>("MatchEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BaseMinute")
                                .HasColumnType("int")
                                .HasColumnName("BaseMinute");

                            b1.Property<int?>("StoppageMinute")
                                .HasColumnType("int")
                                .HasColumnName("StoppageMinute");

                            b1.HasKey("MatchEventId");

                            b1.ToTable("MatchEvents", "sports");

                            b1.WithOwner()
                                .HasForeignKey("MatchEventId");
                        });

                    b.Navigation("Minute")
                        .IsRequired();
                });

            modelBuilder.Entity("SportsStatistics.Domain.MatchTracking.PlayerEvents.PlayerEvent", b =>
                {
                    b.HasOne("SportsStatistics.Domain.Fixtures.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsStatistics.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SportsStatistics.Domain.MatchTracking.Minute", "Minute", b1 =>
                        {
                            b1.Property<Guid>("PlayerEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BaseMinute")
                                .HasColumnType("int")
                                .HasColumnName("BaseMinute");

                            b1.Property<int?>("StoppageMinute")
                                .HasColumnType("int")
                                .HasColumnName("StoppageMinute");

                            b1.HasKey("PlayerEventId");

                            b1.ToTable("PlayerEvents", "sports");

                            b1.WithOwner()
                                .HasForeignKey("PlayerEventId");
                        });

                    b.Navigation("Minute")
                        .IsRequired();
                });

            modelBuilder.Entity("SportsStatistics.Domain.MatchTracking.SubstitutionEvents.SubstitutionEvent", b =>
                {
                    b.OwnsOne("SportsStatistics.Domain.MatchTracking.SubstitutionEvents.Substitution", "Substitution", b1 =>
                        {
                            b1.Property<Guid>("SubstitutionEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PlayerOffId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PlayerOffId");

                            b1.Property<Guid>("PlayerOnId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PlayerOnId");

                            b1.HasKey("SubstitutionEventId");

                            b1.HasIndex("PlayerOffId");

                            b1.HasIndex("PlayerOnId");

                            b1.ToTable("SubstitutionEvents", "sports");

                            b1.HasOne("SportsStatistics.Domain.Players.Player", null)
                                .WithMany()
                                .HasForeignKey("PlayerOffId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired();

                            b1.HasOne("SportsStatistics.Domain.Players.Player", null)
                                .WithMany()
                                .HasForeignKey("PlayerOnId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SubstitutionEventId");
                        });

                    b.OwnsOne("SportsStatistics.Domain.MatchTracking.Minute", "Minute", b1 =>
                        {
                            b1.Property<Guid>("SubstitutionEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BaseMinute")
                                .HasColumnType("int")
                                .HasColumnName("BaseMinute");

                            b1.Property<int?>("StoppageMinute")
                                .HasColumnType("int")
                                .HasColumnName("StoppageMinute");

                            b1.HasKey("SubstitutionEventId");

                            b1.ToTable("SubstitutionEvents", "sports");

                            b1.WithOwner()
                                .HasForeignKey("SubstitutionEventId");
                        });

                    b.Navigation("Minute")
                        .IsRequired();

                    b.Navigation("Substitution")
                        .IsRequired();
                });

            modelBuilder.Entity("SportsStatistics.Domain.Teamsheets.TeamsheetPlayer", b =>
                {
                    b.HasOne("SportsStatistics.Domain.Teamsheets.Teamsheet", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamsheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportsStatistics.Domain.Teamsheets.Teamsheet", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
